name: actions
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    # A matrix proves the supported range of Go versions work. This must always
    # include the floor Go version policy of Mosn and the current Go version.
    # Mosn binaries are built with a specific version inside this range.
    #
    # A floor version is required to ensure Mosn can receive security patches.
    # Without one, dependencies become locked to an old version of Go, which
    # itself receives no security patch updates.
    #
    # Note: Mosn might work with a Go version below its supported floor, but
    # users must not depend on this. Mosn's library dependencies are free to
    # features in it supported floor Go version at any time.
    #
    # Note: There are no unit tests in this project, so we run a matrix on
    # build, not test.
    strategy:
      matrix:
        go-version:
          - "1.18"
          - "1.19"  # Current Go version

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Build
        run: go build ./...
